In [ ]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
# import seaborn as sns


In [ ]:
#Importing the dataset
data = pd.read_csv("/content/Advertising_data.csv")
data.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   2210
1   44.5   39.3       45.1   1040
2   17.2   45.9       69.3    930
3  151.5   41.3       58.5   1850
4  180.8   10.8       58.4   1290

#Simple Linear Regression

###initiating the variables

In [ ]:
x = data['TV'].values.reshape(-1,1)
y = data['sales'].values.reshape(-1,1)

#Splitting dataset into training and testing dataset

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_train

array([[284.3],
       [184.9],
       [112.9],
       [ 23.8],
       [290.7],
       [ 19.4],
       [293.6],
       [ 18.7],
       [134.3],
       [ 25.6],
       [100.4],
       [ 80.2],
       [188.4],
       [177. ],
       [125.7],
       [209.6],
       [142.9],
       [184.9],
       [222.4],
       [241.7],
       [ 17.2],
       [120.5],
       [ 89.7],
       [191.1],
       [ 75.5],
       [193.2],
       [ 85.7],
       [266.9],
       [ 39.5],
       [261.3],
       [ 13.2],
       [193.7],
       [296.4],
       [265.6],
       [214.7],
       [149.7],
       [131.7],
       [ 57.5],
       [240.1],
       [141.3],
       [180.8],
       [ 97.2],
       [220.5],
       [140.3],
       [255.4],
       [ 96.2],
       [ 66.1],
       [239.3],
       [175.7],
       [240.1],
       [ 17.9],
       [230.1],
       [283.6],
       [171.3],
       [199.1],
       [123.1],
       [131.1],
       [ 25.1],
       [163.5],
       [248.8],
       [202.5],
       [ 13.1],
       [

#Fitting linear regression to our training set to train our model

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

#Predicting the test set result

In [ ]:
y_pred = reg.predict(x_test)
#y_pred

R-squared is a statistical measure that represents the goodness of fit of a regressional model.The ideal value for r-square to 1, the better is the model fitted .

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6714477229302764

In [ ]:
output = reg.predict([[300.06]])
output

array([[2116.45849373]])

In [ ]:
#intercept
reg.intercept_

array([723.94598308])

In [ ]:
reg.coef_

array([[4.64078021]])